python /data/leuven/370/vsc37045/thesis/gpt/generate_dataset.py \
    --train_json_path "/scratch/leuven/370/vsc37045/resource/gpt/separation/train.json" \
    --val_json_path "/scratch/leuven/370/vsc37045/resource/gpt/separation/val.json" \
    --train_answers_path "/scratch/leuven/370/vsc37045/resource/gpt/prompts/train_answers.txt" \
    --val_answers_path "/scratch/leuven/370/vsc37045/resource/gpt/prompts/val_answers.txt" \
    --train_dataset_path "/scratch/leuven/370/vsc37045/resource/gpt/dataset/train.json" \
    --val_dataset_path "/scratch/leuven/370/vsc37045/resource/gpt/dataset/val.json" \
    --test_json_path "/scratch/leuven/370/vsc37045/resource/gpt/separation/test.json" \
    --test_answers_path "/scratch/leuven/370/vsc37045/resource/gpt/prompts/test_answers.txt" \
    --test_dataset_path "/scratch/leuven/370/vsc37045/resource/gpt/dataset/test.json" \
    --train_val_dataset_path "/scratch/leuven/370/vsc37045/resource/gpt/dataset/train+val.json"