model_save_dir: "/leonardo_work/EUHPC_B25_058/aleksa_files/downloaded_work/resource/dpo/experiment_gpt2_large"
comat_config: "/leonardo_work/EUHPC_B25_058/aleksa_files/downloaded_work/code/evaluator/comat.yml"
gsam_config: "/leonardo_work/EUHPC_B25_058/aleksa_files/downloaded_work/code/evaluator/gsam.yml"
reward_config: "/leonardo_work/EUHPC_B25_058/aleksa_files/downloaded_work/code/evaluator/reward_config.yml" 
loss_type: "sigmoid"
learning_rate: 5e-06
weight_decay: 0.0
beta: 0.1
ref_model_mixup_alpha: 1.0
ref_model_sync_steps: 512
lr_scheduler_type: "linear"
